# Generated by Django 4.2.3 on 2023-08-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_webseite"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Webseite",
            new_name="Website",
        ),
    ]
