# Generated by Django 4.2.3 on 2023-09-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_webseite_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Umfrage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frage_1", models.CharField(max_length=500)),
                ("frage_2", models.CharField(max_length=500)),
                ("frage_3", models.CharField(max_length=500)),
                ("frage_4", models.CharField(max_length=500)),
                ("frage_5", models.CharField(max_length=500)),
                ("frage_6", models.CharField(max_length=500)),
                ("frage_7", models.CharField(max_length=500)),
                ("frage_8", models.CharField(max_length=500)),
                ("frage_9", models.CharField(max_length=500)),
                ("frage_10", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="website",
            name="groups",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="name",
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="parsed",
            field=models.BooleanField(default=False),
        ),
    ]
