# Generated by Django 4.2.3 on 2023-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_umfrage_website_groups_website_name_website_parsed"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="groups_link",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="parsed_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="website",
            name="regex_link",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
